# Generated by Django 5.1.2 on 2024-11-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_property_created_by_property_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rating',
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='2024-01-01 00:00:00', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='2024-01-01 00:00:00', upload_to='properties/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
