# Generated by Django 5.1.2 on 2024-11-17 03:21

from django.db import migrations, models
from django.utils.timezone import now as timezone_now  # Import timezone.now

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_property_created_by_remove_property_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone_now),  # Fixed here
            preserve_default=False,
        ),
    ]
