# Generated by Django 5.1.2 on 2024-11-17 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sliderproperty_property_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderProperty',
        ),
    ]
