# Generated by Django 5.1.2 on 2024-11-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_sliderproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
