# Generated by Django 5.1.2 on 2024-11-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sliderproperty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderproperty',
            name='link',
        ),
        migrations.AddField(
            model_name='sliderproperty',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
