# Generated by Django 5.1.2 on 2024-11-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('property_location', models.CharField(max_length=100)),
                ('property_description', models.TextField()),
                ('property_image', models.ImageField(blank=True, upload_to='agents_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
