# Generated by Django 5.1.2 on 2024-11-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_propertyinteriorhome_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinteriorhome',
            name='image',
            field=models.ImageField(upload_to='Interiors/'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
